apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 8098
      targetPort: 8098
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/pweb-idp/backend:v0.0.6
        ports:
        - containerPort: 8098
        env:
        - name: PG_HOST
          value: "postgresql"
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: "warproject"
        - name: PG_USERNAME
          value: "admin"
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-credentials
              key: password
              optional: false
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: "admin"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: rabbitmq-password
              optional: false